## **Artificial Neural Network**

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense
import numpy as np

## Creating dataset for an And Gate

In [ ]:
x=np.array([[0,0], [0,1], [1,0], [1,1]], "uint8")
y=np.array([[0], [0], [0], [1]], "uint8")

# CREATING A SEQUENTIAL MODEL USING TENSORFLOW

In [ ]:
model=Sequential()
model.add(Dense(units=1, activation='sigmoid', input_dim=2))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(x, y, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 5ms/step - loss: 0.4832 - accuracy: 1.0000
Epoch 2/500
1/1 [==============================] - 0s 6ms/step - loss: 0.4830 - accuracy: 1.0000
Epoch 3/500
1/1 [==============================] - 0s 7ms/step - loss: 0.4829 - accuracy: 1.0000
Epoch 4/500
1/1 [==============================] - 0s 4ms/step - loss: 0.4828 - accuracy: 1.0000
Epoch 5/500
1/1 [==============================] - 0s 6ms/step - loss: 0.4827 - accuracy: 1.0000
Epoch 6/500
1/1 [==============================] - 0s 7ms/step - loss: 0.4825 - accuracy: 1.0000
Epoch 7/500
1/1 [==============================] - 0s 5ms/step - loss: 0.4824 - accuracy: 1.0000
Epoch 8/500
1/1 [==============================] - 0s 13ms/step - loss: 0.4823 - accuracy: 1.0000
Epoch 9/500
1/1 [==============================] - 0s 5ms/step - loss: 0.4821 - accuracy: 1.0000
Epoch 10/500
1/1 [==============================] - 0s 8ms/step - loss: 0.4820 - accuracy: 1.0000
Epoch 11/500
1/1 [==========

In [ ]:
print(model.layers[0].get_weights())

[array([[0.9148763 ],
       [0.81399083]], dtype=float32), array([-1.3758795], dtype=float32)]


In [ ]:
model.predict(x)

array([[0.20167157],
       [0.3631106 ],
       [0.38674787],
       [0.58734185]], dtype=float32)

# CREATING DATABASE FOR A XOR GATE

In [ ]:
x = [[0,0], [0,1], [1,0], [1,1]]
y = [[0], [1], [1], [0]]

In [ ]:
xor = Sequential()
xor.add(Dense(2, input_dim=2, activation='sigmoid')) #hidden layer with 2 neurons
xor.add(Dense(1, activation='sigmoid')) # output layer with 1 neuron
xor.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
xor.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [ ]:
xor.fit(x ,y, epochs=900)

Epoch 1/900
1/1 [==============================] - 0s 7ms/step - loss: 0.6548 - accuracy: 0.7500
Epoch 2/900
1/1 [==============================] - 0s 6ms/step - loss: 0.6547 - accuracy: 0.7500
Epoch 3/900
1/1 [==============================] - 0s 5ms/step - loss: 0.6546 - accuracy: 0.7500
Epoch 4/900
1/1 [==============================] - 0s 4ms/step - loss: 0.6546 - accuracy: 0.7500
Epoch 5/900
1/1 [==============================] - 0s 6ms/step - loss: 0.6545 - accuracy: 0.7500
Epoch 6/900
1/1 [==============================] - 0s 5ms/step - loss: 0.6544 - accuracy: 0.7500
Epoch 7/900
1/1 [==============================] - 0s 6ms/step - loss: 0.6543 - accuracy: 0.7500
Epoch 8/900
1/1 [==============================] - 0s 7ms/step - loss: 0.6542 - accuracy: 0.7500
Epoch 9/900
1/1 [==============================] - 0s 5ms/step - loss: 0.6541 - accuracy: 0.7500
Epoch 10/900
1/1 [==============================] - 0s 5ms/step - loss: 0.6540 - accuracy: 0.7500
Epoch 11/900
1/1 [===========

In [ ]:
xor.get_weights()

[array([[-2.6023152, -1.7936373],
        [-3.1308591, -1.9301214]], dtype=float32),
 array([0.7033444, 2.61016  ], dtype=float32),
 array([[-2.9223816],
        [ 2.0391912]], dtype=float32),
 array([-0.62924993], dtype=float32)]

In [ ]:
xor.predict(x)

array([[0.33523917],
       [0.61946005],
       [0.5997341 ],
       [0.4640251 ]], dtype=float32)

# DEEP NEURAL NETWORK TO PREDICT HAND WRITTEN DIGIT RECOGNITION

In [ ]:
## IMPORTING THE DATASET
from sklearn.datasets import load_breast_cancer
Data = load_breast_cancer()

In [ ]:
print(Data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [ ]:
features = Data.data
target = Data.target

print(features.shape)
print(target.shape)

(569, 30)
(569,)


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(455, 30)
(455,)
(114, 30)
(114,)


In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(32, input_dim = 30, activation='relu')) ## hidden layer is 1
model.add(Dense(64, activation='relu')) ## hidden layer 2
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                992       
_________________________________________________________________
dense_1 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 65        
Total params: 3,169
Trainable params: 3,169
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# model.fit(X_train, y_train, epochs=10, batch_size=32)
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3343 - accuracy: 0.9165
Epoch 2/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2274 - accuracy: 0.9187
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2128 - accuracy: 0.9209
Epoch 4/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2271 - accuracy: 0.9143
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2139 - accuracy: 0.9121
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2558 - accuracy: 0.8945
Epoch 7/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2332 - accuracy: 0.9143
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: 0.1918 - accuracy: 0.9297
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2568 - accuracy: 0.9011
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3311 - accuracy: 0.9165


In [ ]:
scores = model.evaluate(X_test, y_test)
print(scores) ### returns loss and accuracy

4/4 [==============================] - 1s 3ms/step - loss: 0.5258 - accuracy: 0.8684
[0.5257763862609863, 0.8684210777282715]


In [ ]:
predictions = model.predict(X_test)
label=[]
for pred in predictions:
  if pred>=0.5:
    print("Malignent")
  else:
    print("Benign")

Benign
Benign
Malignent
Benign
Malignent
Malignent
Malignent
Benign
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Benign
Malignent
Malignent
Benign
Benign
Benign
Benign
Benign
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Benign
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Benign
Malignent
Benign
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Benign
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Benign
Benign
Benign
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Benign
Malign